# See https://github.com/shawhahnlab/igseqhelper
include: "setup.smk"
include: "reads.smk"
include: "germline.smk"
include: "isolates.smk"
include: "sonar.smk"
include: "structure.smk"
include: "results.smk"
